package com.example.admin.samplegame;

import java.util.ArrayList;

/**
 * Created by admin on 11-02-2018.
 */

public class Image {
    private Integer imageId;
    private  String description;

    public Image(Integer imageId, String description) {
        this.imageId = imageId;
        this.description = description;
    }

    public Integer getImageId() {
        return imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public static Image getImageIdByPos(ArrayList<Image> images,Integer position){
        return images.get(position);
    }
    public static ArrayList<Image> getImages(){
        ArrayList<Image> images=new ArrayList<Image>();
        images.add(new Image(R.drawable.sample_2,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_3,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_4,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_5,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_0,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_1,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_2,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_3,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_4,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_5,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_0,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_1,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_2,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_3,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_4,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_5,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_0,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        images.add(new Image(R.drawable.sample_1,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in pharetra diam. Mauris semper mi eget pulvinar malesuada. Quisque metus tellus, porta in ullamcorper at, blandit in quam. Pellentesque a metus sed dolor tempor consequat. Maecenas feugiat tellus in dui pretium malesuada. Etiam nec lorem ut odio ultrices sollicitudin ac vel lorem. Maecenas non velit arcu. Nullam id ex eu diam facilisis aliquet. Nam quis suscipit ligula. Nulla facilisi. Maecenas in gravida dui, a faucibus ante. Donec ullamcorper vestibulum orci quis lobortis. Praesent pulvinar metus eget sodales sollicitudin. Donec porttitor ligula a justo varius, congue convallis velit maximus. Suspendisse vitae elementum leo, vitae posuere sem. Phasellus posuere, metus a accumsan pulvinar, arcu dui pharetra ipsum, eget viverra sem velit quis lectus."));
        return images;
    }
}
